cart/urls.py
from django.urls import path
from .views import  *

app_name = "cart"
urlpatterns = [
    

    path('',view_cart, name='cart_list'),



    path('delete/<int:id>/',remove_from_cart, name='remove_from_cart'),

    
    path('empty/',empty_cart, name='empty_cart'),
    
    path('checkout/',checkout, name='checkout'),

    path('add_to_cart/<int:product_id>/',add_to_cart, name='add_to_cart'),
    
]

e_commerce/urls.py
from django.contrib import admin
from django.urls import path,include
 
from django.conf import settings
from django.conf.urls.static import static

from cart import views

urlpatterns = [
    path('admin/', admin.site.urls),

    path("cart/", include("cart.urls")),
    path("users/", include("users.urls")),
    path("", include("home.urls")),

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from .views import  *

app_name = "home"
urlpatterns = [
    

    path('',homepage, name='home'),
    path('products/',productsPage, name='products'),
    path('search_products/',searchProducts, name='search_products'),
    path('contact-us/',contactUs, name='contactUs'),



    
]

users/urls.py
from django.urls import path
from .views import  *

app_name = "users"
urlpatterns = [
    
    path('logout/',user_logout, name='logout'),

    path('login/',user_login, name='login'),

    path('register/',user_register, name='register'),

]

users/models.py
from django.db import models
from datetime import datetime,timedelta

# Create your models here.
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager,Group
from django.contrib.auth.models import PermissionsMixin,Permission







class UserAccountManager(BaseUserManager):
    use_in_migrations = True
    

    def create_user(self, username,email, password=None):
        if not username:
            raise ValueError("Username invalid")
        if not email:
            raise ValueError("Email invalid")

        user = self.model(username=username,email=self.normalize_email(email))
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, username,email, password):
        user = self.create_user(username=username,email=email,password=password)
        # user.is_active = True
        # user.is_admin = True
        # user.is_superuser = True
        user.is_staff = True
        user.save(using=self._db)
        return user




from django.core.files.storage import default_storage
import os
from django.core.files.storage import FileSystemStorage





# python manage.py dumpdata users.user --output users/fixtures/users.test.json
class User(AbstractBaseUser, PermissionsMixin):
    """ BmUser model """
    email = models.EmailField(max_length=250, unique=True,null=True,blank=True)
    password = models.CharField(max_length=250,null=True,blank=True)
    date_joined = models.DateTimeField(verbose_name='date joined',auto_now_add=True,null=True,blank=True)
    last_login = models.DateTimeField(verbose_name='last login',auto_now_add=True,null=True,blank=True)
    is_staff = models.BooleanField(default=False,null=True,blank=True)    # admin
    is_enabled = models.BooleanField(default=True,null=True,blank=True)
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['password',]

    objects = UserAccountManager()

    def __str__(self):
        return f"{self.email}"
  
    
    def has_module_perms(self, app_label):
        return True

    class Meta:
        ordering = ['id']



class Customer(models.Model):
    user=models.ForeignKey(
        User,
        on_delete=models.PROTECT,
        null=True,blank=True
    )
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    address = models.ManyToManyField(
        "users.Address",blank=True
    )
    email=models.CharField(null=True,blank=True,max_length=100)
    def __str__(self):
        return f"{self.first_name} {self.last_name}"
    
    class Meta:
        verbose_name = "Customers"
        verbose_name_plural = "Customers"



# python manage.py dumpdata users.Regions --output users/fixtures/Regions.test.json
class Regions(models.Model):
    name=models.CharField(max_length=100)

    def __str__(self):
        return self.name
    class Meta:
        verbose_name = "Regions"
        verbose_name_plural = "Regions"


class Address(models.Model):
    region=models.ForeignKey(
        Regions,
        on_delete=models.PROTECT
    )
    address=models.TextField()
    phone_number = models.CharField(max_length=15,null=True,blank=True)
    note=models.TextField()

    def __str__(self):
        return self.address
    class Meta:
        verbose_name = "Address"
        verbose_name_plural = "Address"
    

users/forms.py
from django import forms
from django.forms import Form
from django.contrib.auth.forms import UserChangeForm
from .models import User


class CustomUserCreationForm(forms.ModelForm):
    email = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = '__all__'

    def save(self, commit=True):
        user = super(CustomUserCreationForm, self)
        # user.first_name = self.cleaned_data.get('first_name')
        # user.last_name = self.cleaned_data.get('last_name')
        user.email = self.cleaned_data.get('email')
        user.is_staff = self.cleaned_data.get('is_staff')
        # user.phone = self.cleaned_data.get('phone')
        # user.gender = self.cleaned_data.get('gender')
        
        # user.is_active = self.cleaned_data.get('is_active')
        user.is_enabled = self.cleaned_data.get('is_enabled')
        user.is_superuser = self.cleaned_data.get('is_superuser')
        user.set_password(self.cleaned_data.get('password'))        

        if commit:
            user.save()
            
        return user


class CustomUserChangeForm(UserChangeForm):
    email = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = '__all__'


class LoginForm(Form):
    class Meta(Form):
        model = User
        fields = ['email', 'password']

users/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login

from users.models import Customer, User

def user_login(request):
    if request.method == 'POST':
        email = request.POST['email']
        password = request.POST['password']

        if(email=="" or password==""):
            if(email==""):
                error_message = 'Email field is required'
                return render(request, 'login.html', {'error_message': error_message})
            if(password==""):
                error_message = 'Password field is required'
                return render(request, 'login.html', {'error_message': error_message})
        
        user = authenticate(email=email, password=password)
        if user is not None:
            login(request, user)
            return redirect('/')  # Replace 'home' with the appropriate URL name
        else:
            error_message = 'Invalid username or password. Please try again.'
            return render(request, 'login.html', {'error_message': error_message})
        
    cart = request.session.get('cart', [])
    
    total_qty=0
    for item in cart:
        total_qty+=item['qty']

    context = {
        'total_qty':total_qty,
        'cart': cart,
    }
    return render(request, 'login.html',context)


from django.contrib.auth import logout
def user_logout(request):

    logout(request)

    return redirect("/")

def user_register(request):
    if request.method == 'POST':
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        email = request.POST['email']
        password = request.POST['password']
        
        if(email=="" or password=="" or first_name=="" or last_name==""):
            if(email==""):
                error_message = 'Email field is required'
            if(password==""):
                error_message = 'Password field is required'
            return render(request, 'register.html', {'error_message': error_message})
            
        if(User.objects.filter(email=email).exists()):
            error_message = f'{email} is already used'
            return render(request, 'register.html', {'error_message': error_message})
        
        user = User.objects.create(
            email=email,
        )
        user.set_password(password)
        user.save()
        Customer.objects.create(
            user=user,
            first_name=first_name,
            last_name=last_name
                            
        )

        if user is not None:
            print("test")
            cart = request.session.get('cart', [])  
            context = {
                'cart': cart,
            }
            return redirect("/users/login/")  # Replace 'home' with the appropriate URL name
        
        
    cart = request.session.get('cart', [])  
    total_qty=0
    for item in cart:
        total_qty+=item['qty']

    context = {
        'total_qty':total_qty,
        'cart': cart,
    }
    return render(request, 'register.html',context)

users/templates/login.html
{% extends 'layout.html' %}



{% block title %} Login {% endblock %}

{% block links %} 
<li class="nav-item ">
  <a class="nav-link " href="{% url 'home:home' %}">Home <span class="sr-only">(current)</span></a>
  </li>

  <li class="nav-item">
  <a class="nav-link" href="{% url 'home:products' %}">Products</a>
  </li>
  {% comment %} <li class="nav-item">
  <a class="nav-link" href="/shop/customize">customize</a>
  </li>
{% endcomment %}
  <li class="nav-item">
  <a class="nav-link"  href="{% url 'home:contactUs' %}">Contact Us</a>
  </li>
  
{% endblock %}


{% block links1 %} 
<li class="nav-item ">
  <a class="nav-link " href="{% url 'home:home' %}">Home <span class="sr-only">(current)</span></a>
  </li>

  <li class="nav-item">
  <a class="nav-link" href="{% url 'home:products' %}">Products</a>
  </li>
  {% comment %} <li class="nav-item">
  <a class="nav-link" href="/shop/customize">customize</a>
  </li>
{% endcomment %}
  <li class="nav-item">
  <a class="nav-link"  href="{% url 'home:contactUs' %}">Contact Us</a>
  </li>
  
{% endblock %}
{% block main %} 
<div class="container">
    <h2 class="title-sell">Login</h2>
    <div class="row justify-content-center" >
        <div class="col-md-4 col-md-offset-4">

            {% if  error_message%}
            <div class="alert alert-danger">
                {{error_message}}
            </div>
            {% endif %}

            {% if not user.is_authenticated %}



        <form action="/users/login/" method="post" class="">
            {% csrf_token %}
            <div class="form-group">
                <label style="color: #33383b">Email:</label>
                <input type="text" class="form-control" name="email" placeholder="Email" required>
                {% comment %} @error('email')<span class="text-danger">{{ $message }} </span>@enderror {% endcomment %}
            </div>
            <div class="form-group">
                <label style="color: #33383b">Password:</label>
                <input type="password" class="form-control" name="password" placeholder="Password" required>
                {% comment %} @error('password')<span class="text-danger">{{ $message }}</span> @enderror {% endcomment %}
            </div>
            <button type="submit" class="btn btn-block btn-cart">Login</button>
            <p class="text-center" style="color: #33383b">Dont have an account?
                <a href="{% url 'users:register' %}" class="text-center text-green">Sign Up</a>
            </p>
        </form>
        {% else %}
            logout
        {% endif %}

    </div>
    </div>
    <br>
</div>
{% endblock %}

users/templates/register.html
{% extends 'layout.html' %}



{% block title %} Sign Up {% endblock %}
{% block links %} 
<li class="nav-item ">
  <a class="nav-link " href="{% url 'home:home' %}">Home <span class="sr-only">(current)</span></a>
  </li>

  <li class="nav-item">
  <a class="nav-link" href="{% url 'home:products' %}">Products</a>
  </li>
  {% comment %} <li class="nav-item">
  <a class="nav-link" href="/shop/customize">customize</a>
  </li>
{% endcomment %}
  <li class="nav-item">
  <a class="nav-link"  href="{% url 'home:contactUs' %}">Contact Us</a>
  </li>
  
{% endblock %}


{% block links1 %} 
<li class="nav-item ">
  <a class="nav-link " href="{% url 'home:home' %}">Home <span class="sr-only">(current)</span></a>
  </li>

  <li class="nav-item">
  <a class="nav-link" href="{% url 'home:products' %}">Products</a>
  </li>
  {% comment %} <li class="nav-item">
  <a class="nav-link" href="/shop/customize">customize</a>
  </li>
{% endcomment %}
  <li class="nav-item">
  <a class="nav-link"  href="{% url 'home:contactUs' %}">Contact Us</a>
  </li>
  
{% endblock %}

{% block main %} 
<div class="container">
    <form action="/users/register/" method="POST">
        {% csrf_token %}
    <h2 class="title-sell">Registration</h2>
    
  
    <div class="row justify-content-center" >

        <div class="form-group col-md-6 text-center">
        {% if  error_message%}
        <div class="alert alert-danger">
            {{error_message}}
        </div>
        {% endif %}
    </div>
    </div>


    <div class="row justify-content-center" >

        <div class="form-group col-md-3">

            
                <label style="color: #33383b">Firstname:</label>
                <input type="text" class="form-control" name="first_name" placeholder="Firstname" required>
        </div>

        <div class="form-group col-md-3">
            <label style="color: #33383b">Lastname:</label>
            <input type="text" class="form-control" name="last_name" placeholder="Lastname" required>
        </div>
       
    </div>
    <div class="row justify-content-center  " >
        <div class="form-group col-md-3">
            <label style="color: #33383b">Email:</label>
            <input type="text" class="form-control" name="email" placeholder="Email"  required>
        </div>
        <div class="form-group col-md-3">
            <label style="color: #33383b">Password:</label>
            <input type="password" class="form-control" name="password" placeholder="Password" required>
        </div>
    </div>

   
    <div class="row justify-content-center">
            <div class="col-lg-3">
                <button type="submit" class="btn btn-block btn-cart">Sign Up</button>
                <p class="text-center" style="color: #33383b">Already has account?
                    <a href="{% url 'users:login' %}" class="text-center text-green">Login</a>
                </p>
            </div>
    </div>
        
        </form>
    </div>
    </div>
    <br>
</div>
{% endblock %}