cart/urls.py
from django.urls import path
from .views import  *

app_name = "cart"
urlpatterns = [
    

    path('',view_cart, name='cart_list'),



    path('delete/<int:id>/',remove_from_cart, name='remove_from_cart'),

    
    path('empty/',empty_cart, name='empty_cart'),
    
    path('checkout/',checkout, name='checkout'),

    path('add_to_cart/<int:product_id>/',add_to_cart, name='add_to_cart'),
    
]

e_commerce/urls.py
from django.contrib import admin
from django.urls import path,include
 
from django.conf import settings
from django.conf.urls.static import static

from cart import views

urlpatterns = [
    path('admin/', admin.site.urls),

    path("cart/", include("cart.urls")),
    path("users/", include("users.urls")),
    path("", include("home.urls")),

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from .views import  *

app_name = "home"
urlpatterns = [
    

    path('',homepage, name='home'),
    path('products/',productsPage, name='products'),
    path('search_products/',searchProducts, name='search_products'),
    path('contact-us/',contactUs, name='contactUs'),



    
]

cart/models.py
from django.db import models


# python manage.py dumpdata cart.Status --output cart/fixtures/Status.test.json
class Status(models.Model):
    name = models.CharField(max_length=100)
    listed=models.BooleanField(default=True)

    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name = "Status"
        verbose_name_plural = "Status"



# python manage.py dumpdata cart.Category --output cart/fixtures/Category.test.json
class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Categories"
        verbose_name_plural = "Categories"


def uploadedform(object,filename):
    try:
        import pathlib
        file_extension = pathlib.Path(filename).suffix
        return f'products/{object.name}/{object.name}{file_extension}'

    except Exception as e:
        print(f"error uploading id to minio,{e}")
        

from django_resized import ResizedImageField


TEXT_COLOR = [
        ('text-green', 'text-green'),
        ('text-black', 'text-black'),
        ('text-white', 'text-white'),
]


# python manage.py dumpdata cart.Product --output cart/fixtures/Product.test.json
class Product(models.Model):
    name = models.CharField(max_length=100,unique=True)
    description = models.TextField(null=True,blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    category = models.ForeignKey(Category, on_delete=models.PROTECT,null=True,blank=True)
    image=ResizedImageField(null=True,blank=True,upload_to=uploadedform)
    status=models.ForeignKey(
        Status,
        on_delete=models.PROTECT,
        null=True,blank=True,default=1
    )
    stock = models.IntegerField()
    color=models.CharField(max_length=50, choices=TEXT_COLOR,default='text-black')
    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name = "Products"
        verbose_name_plural = "Products"



class Order(models.Model):
    order_id=models.CharField(max_length=15)
    customer = models.ForeignKey(
        "users.Customer", on_delete=models.PROTECT,
    )
    total_price = models.DecimalField(max_digits=10, decimal_places=2)
    address= models.ForeignKey(
        "users.Address", on_delete=models.PROTECT
    )
    order_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"#{self.order_id}"

class OrderItem(models.Model):
    order = models.ForeignKey(
        Order, on_delete=models.PROTECT
    )
    product = models.ForeignKey(
        Product, on_delete=models.PROTECT
    )
    quantity = models.PositiveIntegerField()

cart/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from settings.models import Settings
from users.models import Address, Customer, Regions
from users.tasks import send_email
from .models import Order, OrderItem, Product
from django.http import HttpResponse




def add_to_cart(request, product_id):
    product = Product.objects.get(pk=product_id)
    
    if 'cart' not in request.session:
        request.session['cart'] = []
    
    cart = request.session['cart']


    product_found=False
    for item in cart:
        if item['id'] == product_id:
            item['qty'] += 1  # Increment the quantity by 1
            item['total_price']=float(item['qty'])*float(item['price'])
            product_found = True
            break

    if not product_found:
        cart.append({
            'id': product.pk,
            'name': product.name,
            'description': product.description,
            'price': str(product.price),
            'image': product.image.url,
            'qty':1,
            'total_price':str(product.price)
        })
    request.session.modified = True

    total_qty=0
    for item in cart:
        total_qty+=item['qty']
    return HttpResponse(total_qty)

def view_cart(request):
    cart = request.session.get('cart', [])
    total_price = sum(float(item['total_price']) for item in cart)
    
    settings=Settings.objects.get()

    total_qty=0
    for item in cart:
        total_qty+=item['qty']

    context = {
        'total_qty':total_qty,
        'cart': cart,
        'total_price': total_price,
        "settings":settings
    }

    
    return render(request, 'view_cart.html', context)




def empty_cart(request):
    if(request.method == 'POST'):
        if 'cart'  in request.session:
            del request.session['cart']

        return redirect('/cart')

def remove_from_cart(request,id):
    cart = request.session.get('cart', [])

    # Remove the item at the specified index
    del cart[id-1]

    # Update the session with the modified cart
    request.session['cart'] = cart

    return redirect('/cart')


from datetime import datetime
from decimal import Decimal


def checkout(request):
        
    cart = request.session.get('cart', [])
    total_price = sum(float(item['total_price']) for item in cart)
    if(len(cart)==0):
        return redirect("/products/")
    settings=Settings.objects.get()

    if(request.method == 'POST'):
        user=None
        if request.user.is_authenticated:
            user=request.user
            address_type = request.POST.get('type')
            customer=Customer.objects.get(user=request.user)
            if(address_type=="choose"):
                # auth ,select from saved address
                selected_address = request.POST.get('selected_address')
            
                address=Address.objects.get(pk=int(selected_address))

                
                order_id=generate_random_id()
                order=Order.objects.create(
                    total_price=total_price,
                    customer=customer,
                    address=address,
                    order_id=order_id
                )
                for item in cart:
                    product=Product.objects.get(id=item['id'])
                    product.stock=product.stock-item['qty']
                    product.save()
                    OrderItem.objects.create(
                        order=order,
                        product=product,
                        quantity=item['qty'],
                    )
                if 'cart'  in request.session:
                    del request.session['cart']

                html_customer=f"""
                <p>Dear Customer {customer.first_name} {customer.last_name},</p>
                <p>Your order has been processed</p>
                 <p>Order Number:{order.order_id}</p>
                 <p>Total price:{total_price}$</p>
                <p>You will receive it within 2-3 days</p>
                """
            
                try:
                    send_email.apply_async(args=(f'PetsNClaws Order',html_customer,user.email),countdown=120)
                except Exception as e:
                    print(f"email didnt send,{e}")


                try:
                    html=f"""
                    <h3>New Order  from {customer.first_name} {customer.last_name} </h3>
                    <p>Hello Dear,<br> You have new order with id=#{order.order_id} <br>total price={total_price}$<br>Delivery address= {address.region.name},{address.address}</p>
                    <p>For more details <a style="color:red" href='{settings.admin_link}/cart/orderitem/?order__id__exact={order.pk}' >click here</a></p>
                    """
                    send_email.delay(f'PetsNClaws New Order',html,settings.reciever_email)
                except Exception as e:
                    print(f"email didnt send,{e}")


                context={
                    "success":'success',
                    "date": datetime.now().strftime("%b %d, %Y"),
                    "order_id":order_id,
                    "address":f"{address.region.name},{address.address}"
                }
                return JsonResponse(context)
            else:
                # auth but new address
                phone = request.POST['phone']
                region=request.POST['region']
                address=request.POST['address']
                note = request.POST['note']
                region=Regions.objects.get(id=region)

                address=Address.objects.create(
                    region=region,
                    address=address,
                    note=note,
                    phone_number=phone
                ) 
                customer.address.add(address)

                order_id=generate_random_id()
                order=Order.objects.create(
                    total_price=total_price,
                    customer=customer,
                    address=address,
                    order_id=order_id
                )
                for item in cart:
                    product=Product.objects.get(id=item['id'])
                    product.stock=product.stock-item['qty']
                    product.save()
                    OrderItem.objects.create(
                        order=order,
                        product=product,
                        quantity=item['qty'],
                    )
                if 'cart'  in request.session:
                    del request.session['cart']
                context={
                    "success":'success',
                    "date": datetime.now().strftime("%b %d, %Y"),
                    "order_id":order_id,
                    "address":f"{region.name},{address}"
                }

                html_customer=f"""
                <p>Dear Customer,</p>
                <p>Your order has been processed</p>
                 <p>Order Number:{order.order_id}</p>
                 <p>Total price:{total_price}$</p>
                <p>You will receive it within 2-3 days</p>
                """
                try:
                    send_email.apply_async(args=(f'PetsNClaws Order',html_customer,user.email),countdown=120)
                except Exception as e:
                    print(f"email didnt send,{e}")


                try:
                    html=f"""
                    <h3>New Order  from {customer.first_name} {customer.last_name} </h3>
                    <p>Hello Dear,<br> You have new order with id=#{order.order_id} <br>total price={total_price}$<br>Delivery address= {region.name},{address}</p>
                    <p>For more details <a style="color:red" href='{settings.admin_link}/cart/orderitem/?order__id__exact={order.pk}' >click here</a></p>
                    """
                    send_email.delay(f'PetsNClaws New Order',html,settings.reciever_email)
                except Exception as e:
                    print(f"email didnt send,{e}")




                return JsonResponse(context)
        else:
            # not auth
            firstname = request.POST.get('firstname')
            lastname = request.POST['lastname']
            email = request.POST['email']
            phone = request.POST['phone']
            region=request.POST['region']
            address=request.POST['address']

            note = request.POST['note']

        
            region=Regions.objects.get(id=region)
            
            customer=Customer.objects.create(
                user=user,
                first_name=firstname,
                last_name=lastname,
                email=email
            )
            address=Address.objects.create(
                region=region,
                address=address,
                note=note,
                phone_number=phone
            )
            customer.address.add(address)
            order_id=generate_random_id()
            order=Order.objects.create(
                total_price=total_price,
                customer=customer,
                address=address,
                order_id=order_id
            )
            for item in cart:
                product=Product.objects.get(id=item['id'])
                product.stock=product.stock-item['qty']
                product.save()
                OrderItem.objects.create(
                    order=order,
                    product=product,
                    quantity=item['qty'],
                )
            if 'cart'  in request.session:
                del request.session['cart']



            html_customer=f"""
                <p>Dear Customer,</p>
                <p>Your order has been processed</p>
                 <p>Order Number:{order.order_id}</p>
                 <p>Total price:{total_price}$</p>
                <p>You will receive it within 2-3 days</p>
                """
            try:
                send_email.apply_async(args=(f'PetsNClaws Order',html_customer,user.email),countdown=120)

cart/templates/view_cart.html
{% extends 'layout.html' %}



{% block title %} My Cart {% endblock %}




{% block links %} 
<li class="nav-item ">
  <a class="nav-link " href="{% url 'home:home' %}">Home <span class="sr-only">(current)</span></a>
  </li>

  <li class="nav-item">
  <a class="nav-link" href="{% url 'home:products' %}">Products</a>
  </li>
  {% comment %} <li class="nav-item">
  <a class="nav-link" href="/shop/customize">customize</a>
  </li>
{% endcomment %}
  <li class="nav-item">
  <a class="nav-link" href="{% url 'home:contactUs' %}">Contact Us</a>
  </li>
  
{% endblock %}

{% block links1 %} 
<li class="nav-item ">
  <a class="nav-link " href="{% url 'home:home' %}">Home <span class="sr-only">(current)</span></a>
  </li>

  <li class="nav-item">
  <a class="nav-link" href="{% url 'home:products' %}">Products</a>
  </li>
  {% comment %} <li class="nav-item">
  <a class="nav-link" href="/shop/customize">customize</a>
  </li>
{% endcomment %}
  <li class="nav-item">
  <a class="nav-link" href="{% url 'home:contactUs' %}">Contact Us</a>
  </li>
  
{% endblock %}


{% block main %} 


<div class="container">
    <h2 class="title-sell">My Cart</h2>

   {% if cart|length > 0 %}
   

    <div class="row">
      <div class="col-lg-6">
        <form action="/cart/empty/" method="POST"> 
          {% csrf_token %}
          <button class="form-group btn btn-cart ">
            Clear Cart
            <i class="fa fa-times" aria-hidden="true"></i>
          </button>
        </form>
      </div>
    </div>
    
<div class="shopping-cart">

  <div class="column-labels">
   
    <label class="product-image">image</label>
    <label class="product-details">product</label>
    <label class="product-price">price</label>
    <label class="product-quantity">qty</label>
    <label class="product-removal">remove</label>
    <label class="product-line-price">total</label>
  </div>

    {% for prod in cart %}
    
  
        <div class="product">
          <div class="product-image">
            <img src="{{prod.image}}" class="rounded-circle">
          </div>
          <div class="product-details">
            <div class="product-title h4">{{prod.name}} </div>
            {% comment %} <p class="product-description">{{prod.description}} </p> {% endcomment %}
          </div>
          <div class="product-price">{{prod.price}} {{settings.currency}}</div>
          <div class="product-quantity">
            {% comment %} <input type="text" value="{{prod.qty}}" class="text-center" readonly> {% endcomment %}
            x {{prod.qty}}
          </div>
          <div class="product-removal">
            <a href="/cart/delete/{{ forloop.counter }}/">
              <i class="fas fa-trash text-danger"></i>
            </a>
          </div>
          <div class="product-line-price">{{prod.total_price}} {{settings.currency}}</div>
          
        </div>
    {% endfor %}



  <div class="totals">
    <div class="totals-item">
      <label>Total</label>
      <div class="totals-value" id="cart-subtotal">{{total_price}} {{settings.currency}}</div>
    </div>
  </div>

</div>

  <div class="row justify-content-center">
    <div class="col-lg-3">
      <a class="btn btn-outline float-right btn-block form-group"href="{% url 'home:products' %}">
        Continue Shopping 
        <i class="fa fa-shopping-cart green-icon" aria-hidden="true"></i>
      </a>
    </div>
    <div class="col-lg-3">
        <a class="btn btn-cart btn-block form-group" href="{% url 'cart:checkout' %}" >
          Checkout
          &nbsp;
          <i class="fa fa-credit-card" aria-hidden="true"></i>
        </a>
    </div>
  </div>
  
  {% else %}
  <div class="empty-cart text-center">
   <img src="/assets/empty-cart.png"  class="img-fluid" alt="">
   <h3>Empty cart</h3>
   <p>Add something to make me happy :)</p>
   <a class="btn btn-outline" href="{% url 'home:products' %}">Go Shopping</a>
</div>
  {% endif %}
  <br>

<br>
    
</div>


{% endblock %}